models:
    image: tp33/django
    external_links:
        -  mysql:db
    volumes:
        - ./CS4501:/app
        - ./fixtures:/app/fixtures
    ports:
        - "8001:8000"
    command: bash -c "python manage.py makemigrations my_project && python manage.py migrate && python manage.py loaddata fixtures/db.json && mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/project1/wsgi.py"

exp:
   image: tp33/django
   links:
      - models:models-api
      - es:es
      - kafka:kafka
   ports:
      - "8002:8000"
   volumes:
      - ./exp:/app
   command: bash -c "mod_wsgi-express start-server --reload-on-changes exp/wsgi.py"

web:
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8000:8000"
   volumes:
      - ./web:/app
   command: bash -c "mod_wsgi-express start-server --reload-on-changes --url-alias /static ./static web/wsgi.py"

kafka:
    image: spotify/kafka
    container_name: kafka
    environment:
        ADVERTISED_HOST: kafka
        ADVERTISED_PORT: 9092
    hostname: kafka

es:
    image: elasticsearch:2.0
    container_name: es
    ports:
        - "9200:9200"

batch:
    image: tp33/django
    container_name: batch
    volumes:
        - ./batch:/app
        - ./fixtures:/app/fixtures
    links:
        - kafka:kafka
        - es:es
    command: bash -c "python script.py"


