models:
    image: tp33/django
    external_links:
        -  mysql:db
    volumes:
        - ./CS4501:/app
        - ./fixtures:/app/fixtures
    ports:
        - "8001:8000"
    command: bash -c "python manage.py makemigrations my_project && python manage.py migrate && python manage.py loaddata fixtures/db.json && mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/project1/wsgi.py"

exp:
   image: tp33/django
   links:
      - models:models-api
      - es:es
      - kafka:kafka
   ports:
      - "8002:8000"
   volumes:
      - ./exp:/app
   command: bash -c "mod_wsgi-express start-server --reload-on-changes exp/wsgi.py"

web:
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8000:8000"
   volumes:
      - ./web:/app
   command: bash -c "mod_wsgi-express start-server --reload-on-changes --url-alias /static ./static web/wsgi.py"

kafka:
    image: spotify/kafka
    container_name: kafka
    environment:
        ADVERTISED_HOST: kafka
        ADVERTISED_PORT: 9092
    hostname: kafka

es:
    image: elasticsearch:2.0
    container_name: es
    ports:
        - "9200:9200"

batch:
    image: tp33/django
    container_name: batch
    volumes:
        - ./batch:/app
        - ./fixtures:/app/fixtures
    links:
        - kafka:kafka
        - es:es
    command: bash -c "python script.py"

spark_batch:
    image: tp33/django
    container_name: batch_for_spark
    volumes:
        - ./data:/app
    links:
        - kafka:kafka
    command: bash -c "python script.py"


spark-master:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  external_links:
        -  mysql:db
  container_name: spark-master
  hostname: spark-master
  environment:
    MASTER: spark://spark-master:7077
    SPARK_CONF_DIR: /conf
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./data:/app

spark-worker:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  external_links:
        -  mysql:db
  container_name: spark-worker
  hostname: spark-worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 512m
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - spark-master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./data:/app


