models:
    image: tp33/django
    external_links:
        -  mysql:db
    volumes:
        - ./CS4501:/app
    ports:
        - "8001:8000"
    command: bash -c "python manage.py makemigrations my_project && python manage.py migrate && python manage.py loaddata db.json && mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/project1/wsgi.py"

exp:
   image: tp33/django
   links:
      - models:models-api
   ports:
      - "8002:8000"
   volumes:
      - ./exp:/app
   command: bash -c "mod_wsgi-express start-server --reload-on-changes exp/wsgi.py"

web:
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8000:8000"
   volumes:
      - ./web:/app
   command: bash -c "mod_wsgi-express start-server --reload-on-changes web/wsgi.py"

# talk to TA about broken fixtures