models:
    image: tp33/django
    external_links:
        -  mysql:db
    volumes:
        - ./:/app
    ports:
        - "8001:8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py  && mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/project1/wsgi.py"
