# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='book_to_buy',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='book_to_sell',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='buyer',
        ),
        migrations.DeleteModel(
            name='seller',
        ),
    ]
