# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0002_auto_20170322_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('authenticator', models.CharField(default='', max_length=900)),
            ],
        ),
    ]
